name: Android CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      # Set App Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=SPKM" >> $GITHUB_ENV
      # Configure Gradle memory settings
      - name: Configure Gradle memory
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.jvmargs=-Xmx4g -Xms1g -XX:MaxMetaspaceSize=1g" >> ~/.gradle/gradle.properties
          echo "org.gradle.daemon=true" >> ~/.gradle/gradle.properties
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build
      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble
      # Upload Artifact Build
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repository_name }} - ${{ env.date_today }} - APK release generated
          path: app/build/outputs/apk/fdroid/release/
